#!/bin/bash
# Initialize Ralph Wiggum setup in a project
# Usage: ./tools/setup-project.sh [project-root]

set -euo pipefail

PROJECT_ROOT="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RALPH_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Ralph Wiggum Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if we're in a git repo
if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo "⚠️  Warning: Not in a git repository"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Yy]$ ]] && exit 1
fi

# Core files to copy
CORE_FILES=(
    "loop.sh"
    "PROMPT_plan.md"
    "PROMPT_plan_slc.md"
    "PROMPT_plan_work.md"
    "PROMPT_build.md"
    "AGENTS.md"
    "AUDIENCE_JTBD.md"
    "CLAUDE.md"
)

# Directories to create
DIRS=(
    "specs"
    "src/lib"
    ".cursor/rules"
)

echo "📁 Creating directory structure..."
for dir in "${DIRS[@]}"; do
    mkdir -p "$PROJECT_ROOT/$dir"
    echo "  ✓ Created $dir/"
done
echo ""

echo "📄 Copying core files..."
for file in "${CORE_FILES[@]}"; do
    if [ -f "$RALPH_ROOT/$file" ]; then
        cp "$RALPH_ROOT/$file" "$PROJECT_ROOT/$file"
        echo "  ✓ Copied $file"
    else
        echo "  ⚠️  Warning: $file not found in Ralph setup"
    fi
done
echo ""

# Copy spec template
if [ -f "$RALPH_ROOT/specs/_template.md" ]; then
    cp "$RALPH_ROOT/specs/_template.md" "$PROJECT_ROOT/specs/_template.md"
    echo "  ✓ Copied specs/_template.md"
fi

# Copy LLM review fixture if TypeScript project detected
if [ -f "$PROJECT_ROOT/package.json" ] || [ -f "$PROJECT_ROOT/tsconfig.json" ]; then
    if [ -f "$RALPH_ROOT/src/lib/llm-review.ts" ]; then
        mkdir -p "$PROJECT_ROOT/src/lib"
        cp "$RALPH_ROOT/src/lib/llm-review.ts" "$PROJECT_ROOT/src/lib/llm-review.ts"
        cp "$RALPH_ROOT/src/lib/llm-review.test.ts" "$PROJECT_ROOT/src/lib/llm-review.test.ts"
        echo "  ✓ Copied LLM-as-judge fixture (TypeScript project detected)"
    fi
fi

# Copy Claude Code plugin if it exists
if [ -d "$RALPH_ROOT/.claude/plugins/ralph-wiggum" ]; then
    mkdir -p "$PROJECT_ROOT/.claude/plugins"
    cp -r "$RALPH_ROOT/.claude/plugins/ralph-wiggum" "$PROJECT_ROOT/.claude/plugins/"
    chmod +x "$PROJECT_ROOT/.claude/plugins/ralph-wiggum/hooks/stop-hook.sh" 2>/dev/null || true
    chmod +x "$PROJECT_ROOT/.claude/plugins/ralph-wiggum/scripts/setup-ralph-loop.sh" 2>/dev/null || true
    echo "  ✓ Copied Claude Code plugin (use /ralph-loop in Claude Code)"
fi
echo ""

# Make scripts executable
echo "🔧 Making scripts executable..."
chmod +x "$PROJECT_ROOT/loop.sh" 2>/dev/null || true
if [ -d "$PROJECT_ROOT/tools" ]; then
    chmod +x "$PROJECT_ROOT/tools/"*.sh 2>/dev/null || true
fi
echo "  ✓ Scripts are executable"
echo ""

# Initialize IMPLEMENTATION_PLAN.md if it doesn't exist
if [ ! -f "$PROJECT_ROOT/IMPLEMENTATION_PLAN.md" ]; then
    cat > "$PROJECT_ROOT/IMPLEMENTATION_PLAN.md" << 'EOF'
# Implementation Plan

<!-- Generated by LLM with content and structure it deems most appropriate -->

## Tasks

<!-- Tasks will be added here during planning phase -->

EOF
    echo "  ✓ Created IMPLEMENTATION_PLAN.md"
fi
echo ""

# Prompt for project-specific values
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Project Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Update these files with your project-specific values:"
echo ""
echo "1. AGENTS.md - Add your build/test commands"
echo "2. AUDIENCE_JTBD.md - Define your audience and their jobs"
echo "3. PROMPT_plan.md - Replace [project-specific goal] placeholder"
echo "4. specs/ - Create spec files for your features"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "1. Edit AGENTS.md with your project commands"
echo "2. Create specs in specs/ directory"
echo "3. Run: ./loop.sh plan"
echo "4. Review IMPLEMENTATION_PLAN.md"
echo "5. Run: ./loop.sh 20"
echo ""
